# Generated by Django 2.0.7 on 2018-11-19 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_topic', models.BooleanField(verbose_name='是否话题')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('answer_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Message', verbose_name='回应')),
            ],
        ),
    ]
