# Generated by Django 2.0.7 on 2018-11-22 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20181119_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='answer_to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='clicks_num',
        ),
        migrations.AddField(
            model_name='message',
            name='answer_to_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Message', verbose_name='回应的帖子'),
        ),
        migrations.AddField(
            model_name='message',
            name='answer_to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='回应的人'),
        ),
        migrations.AddField(
            model_name='message',
            name='heat',
            field=models.PositiveIntegerField(default=0, verbose_name='热度'),
        ),
    ]
