# Generated by Django 2.0.7 on 2018-11-26 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20181123_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer_to_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.Message', verbose_name='回应的帖子'),
        ),
        migrations.AlterField(
            model_name='message',
            name='answer_to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_messages', to=settings.AUTH_USER_MODEL, verbose_name='回应的人'),
        ),
    ]
