# Generated by Django 2.0.7 on 2018-11-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20181126_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answer_to_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.Message', verbose_name='回应的话题'),
        ),
    ]
