# Generated by Django 2.0.7 on 2018-11-28 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_message_answer_to_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer_to_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.Message', verbose_name='回应的帖子'),
        ),
        migrations.AlterField(
            model_name='message',
            name='answer_to_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.Message', verbose_name='回应的话题'),
        ),
    ]
