# Generated by Django 2.0.7 on 2018-12-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_message_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answers_num',
            field=models.PositiveIntegerField(default=0, verbose_name='回应数'),
        ),
    ]
