# Generated by Django 2.0.7 on 2018-12-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_message_answers_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='brief',
            field=models.CharField(blank=True, max_length=120, verbose_name='简介'),
        ),
    ]
