# Generated by Django 2.0.7 on 2018-11-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20181119_1717'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='UserGroup',
        ),
    ]
