# Generated by Django 2.0.7 on 2018-11-23 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20181122_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='加入时间')),
                ('is_invite', models.BooleanField(default=False, verbose_name='是否邀请加入')),
                ('role', models.CharField(choices=[('user', '组员'), ('create_user', '组长'), ('manager', '管理员')], db_index=True, default='user', max_length=15, verbose_name='角色')),
            ],
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='create_user',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='status',
            field=models.CharField(choices=[('verifying', '审核中'), ('normal', '使用中')], default='verifying', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=30, verbose_name='小组名'),
        ),
        migrations.AddField(
            model_name='useringroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.UserGroup'),
        ),
        migrations.AddField(
            model_name='useringroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='member_groups',
            field=models.ManyToManyField(related_name='members', through='member.UserInGroup', to='member.UserGroup'),
        ),
    ]
