# Generated by Django 2.0.7 on 2018-12-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20181123_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': '小组', 'verbose_name_plural': '小组'},
        ),
        migrations.AlterModelOptions(
            name='useringroup',
            options={'verbose_name': '组员关系', 'verbose_name_plural': '组员关系'},
        ),
    ]
