# Generated by Django 2.0.7 on 2018-12-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20181205_1006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useringroup',
            unique_together={('user', 'group')},
        ),
    ]
