# Generated by Django 2.0.7 on 2018-12-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20181205_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='人数'),
        ),
    ]
